version: 1.0.{build}
image: Visual Studio 2017

#restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
#package Web Application project for Web Deploy
build:
  project: ERPAdmin.sln
  verbosity: minimal
  publish_wap: true
