version: '2'

services:
  identity.api:
    image: erpadmin/identity.api
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"