version: '2'
# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ERPADMIN_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ERPADMIN_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5105
     # - SpaClient=http://${ERPADMIN_EXTERNAL_DNS_NAME_OR_IP}:5104
      - ConnectionStrings__DefaultConnection=Server=sql.data;Database=ERPAdmin.Services.IdentityDb;User Id=sa;Password=Pass@word 
    #  - MvcClient=http://${ERPADMIN_EXTERNAL_DNS_NAME_OR_IP}:5100              #Local: You need to open your local dev-machine firewall at range 5100-5105.  
    ports:
      - "5105:5105"
      
      
  contractors.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5102
      - ConnectionString=Server=sql.data;Database=ERPAdmin.Services.ContractorsDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity.api:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - EventBusConnection=rabbitmq
    ports:
      - "5102:5102"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
